# Generated by Django 4.2.3 on 2023-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Назава товару')),
                ('description', models.TextField(verbose_name='Характеристики')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('active', models.BooleanField(verbose_name='Активний')),
                ('review', models.TextField(verbose_name='Відгук')),
            ],
        ),
    ]
