# Generated by Django 4.2.3 on 2023-07-15 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name_alter_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='review',
            field=ckeditor.fields.RichTextField(verbose_name='Відгук'),
        ),
    ]
