# Generated by Django 4.2.3 on 2023-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_description_alter_goods_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sale',
            field=models.BooleanField(default=False, help_text='Покахувати є товар зі знижкою ', verbose_name='Є Знижка'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='active',
            field=models.BooleanField(default=False, help_text='Показувати товари чи ні', verbose_name='Активний'),
        ),
    ]
