# Generated by Django 4.2.3 on 2023-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_goods_sale_alter_goods_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='company',
            field=models.CharField(default='Назва компанії за замовчуванням', max_length=200, verbose_name='Назва компанії'),
        ),
    ]
