# Generated by Django 4.2.3 on 2023-07-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_goods_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='company',
            field=models.CharField(default='Без компаніі', max_length=200, verbose_name='Назва компанії'),
        ),
    ]
