# Generated by Django 4.2.3 on 2023-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_tag_goods_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
